### ISSUE TITLE
GNU/Linux Support

### ISSUE THREAD

**Issue by nnn1590** [usagirei/3DS-Theme-Editor#18]
This sentence was translated from Japanese to English by Google translation.
I am now a GNU / Linux user.
However, this editor uses WPF of .net Framework and can not handle easily with .net Core, Mono, Wine. (The screen display is broken in Wine.)
(Also, since Windows is proprietary it is better to correspond to open source OS like GNU / Linux)
Therefore, can you correspond to GNU / Linux?
(There are Qt and Java etc in the cross platform framework.)
<hr>

この文章はGoogle 翻訳によって日本語から英語に翻訳されました。
私は今GNU/Linuxユーザーです。
しかしこのエディタは.net FrameworkのWPFを使用しており、.net CoreやMono、Wineでは容易に扱うことができません。(Wineでは画面表示が壊れます。)
(またWindowsはプロプライエタリなのでGNU/LinuxのようなオープンソースなOSに対応することは良いことでしょう)
そのためGNU/Linuxに対応してもらえませんか？
(クロスプラットフォームなフレームワークにQtやJavaなどがあります。)

**Comment by Algorithmus** [comment]
@nnn1590 I Don't know if usagirei is necessarily interested in making the Usagi editor cross platform, as that's been asked before on other threads, and mostly been ignored, and there's no other real indication that this is something he/she is willing to take up.

However, I am also interested in a more native solution for making 3DS themes on Linux, and have started with making command line tools written in C++ that don't require installing Wine or Mono. You can find that project here: https://gitlab.com/beelzy/kame-tools
I do plan to make a GUI in Qt for it eventually, but I want to tackle the bgm format first. For a completely Wine/mono free theme creation experience.

And Google Translate, because I don't know if you can read English:

@ nnn1590私はusagireiがUsagiエディタをクロスプラットフォームにすることに興味を持っているのかどうかわからないし、それは他のスレッドでも言われ、ほとんど無視されています 取り上げる。

ただし、Linuxで3DSテーマを作成するためのよりネイティブなソリューションにも関心があり、WineやMonoのインストールを必要としないC ++で作成されたコマンドラインツールの作成から始めました。 あなたはここにそのプロジェクトを見つけることができます：https：//gitlab.com/beelzy/kame-tools
最終的にはQtでGUIを作るつもりですが、まずbgmフォーマットに取り組みたいと思います。 完全にワイン/モノの無料テーマ作成の経験のために。

**Comment by nnn1590** [comment]
Thank you!
